version: '3.1'

services:

  mysql:
    build:
      context: ./app/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  hardware:
    build:
      context: ./app/hardware
    restart: always
    depends_on:
      - mysql

  portal:
    build:
      context: ./app/portal
    restart: always
    ports:
      - "5000:5000"
  